### ISSUE TITLE
Auto fill characters bug

### ISSUE THREAD

**Issue by pmros** [princejwesley/Mancy#48] opened 2015-11-11 07:17 UTC
When you type '9', Mancy "autofill" another '9' character. I think it's a issue related to shift keycode and parentheses. When you type "(" or "(quotes), no autofill at all.

**Comment by princejwesley** [comment] 2015-11-11 07:24
@pmros let me look into that

**Comment by princejwesley** [comment] 2015-11-11 15:04
> When you type "(" or "(quotes), no autofill at all.
@pmros I don't understand this part.

**Comment by pmros** [comment] 2015-11-11 16:38
I mean that if you type "[", Mancy autocomplete it with "]". If you type "{", Mancy autocomplete it with "}". But if you type "(", Mancy does not autocomplete it with ")", Mancy does not autocomplete. 

Sorry for my English. I hope you understand me. Thank you.

**Comment by princejwesley** [comment] 2015-11-28 03:52
@pmros Please reopen this ticket if you can reproduce the issue in the latest build

**Comment by pmros** [comment] 2015-12-08 21:25
When you write "?", Mancy show "??".

**Comment by princejwesley** [comment] 2015-12-08 21:28
@pmros I am not able to reproduce this issue. let me try to reproduce it in my linux box

**Comment by pmros** [comment] 2015-12-08 21:38
```
localectl status
```
```
   System Locale: LANG=es_ES.UTF-8
       VC Keymap: n/a
      X11 Layout: es
       X11 Model: pc104
```

**Comment by hugomrdias** [comment] 2016-01-07 01:28
if i call a function auto-fill breaks with the parentheses

```
someFunction())
```

 the first closing parentheses doesnt autocomplete but when i manually type the first closing parentheses it adds another like the example above

**Comment by princejwesley** [comment] 2016-01-07 01:33
@hugomrdias can you test in  `master` branch?

**Comment by hugomrdias** [comment] 2016-01-07 02:31
npm install && npm run package

gives this error

```
npm ERR! Linux 3.19.0-42-generic
npm ERR! argv "/home/hugomrdias/.nvm/versions/node/v5.4.0/bin/node" "/home/hugomrdias/.nvm/versions/node/v5.4.0/bin/npm" "install"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! mancy@2.1.0 postinstall: `electron-rebuild && gulp clean && gulp copy`
npm ERR! Exit status 255
```

**Comment by princejwesley** [comment] 2016-01-07 04:05
@hugomrdias  https://github.com/electronjs/electron-rebuild/issues/39 - related ?

**Comment by hugomrdias** [comment] 2016-01-07 12:20
maybe im try now with node 0.12 npm 2

**Comment by hugomrdias** [comment] 2016-01-07 12:35
worked and the problem is gone but there's no path completion now :/

**Comment by princejwesley** [comment] 2016-01-07 12:52
@hugomrdias update preferences

**Comment by hugomrdias** [comment] 2016-01-07 13:46
perfect @princejwesley release ETA ? :+1: just kidding 
thnx

**Comment by princejwesley** [comment] 2016-01-07 16:57
@hugomrdias this weekend or monday :+1:

**Closed** 2016-03-28 07:07 UTC
Labels: bug, ready for release
