### ISSUE TITLE
Build fails under npm v3

### ISSUE THREAD

**Issue by xgrommx** [princejwesley/Mancy#41] opened 2015-11-08 04:23 UTC
@princejwesley I cannot rebuild Mancy on windows. I have errors about mime module.

**Comment by senthilporunan** [comment] 2015-11-08 04:53
@xgrommx  can you give full error here.. For me it is working good in windows7 ..

**Comment by boneskull** [comment] 2015-11-08 06:47
@xgrommx If you're using npm v3.x, try with v2.x instead.  This worked for me after having problems building on MacOS X.

**Comment by boneskull** [comment] 2015-11-08 06:47
this ticket should be renamed; "Build fails under npm v3"

**Comment by princejwesley** [comment] 2015-11-08 12:47
@xgrommx  [#43](https://github.com/princejwesley/Mancy/issues/43) PR helps ?

**Comment by xgrommx** [comment] 2015-11-08 13:46
@princejwesley Looks like it's solved. Thanks

**Comment by xgrommx** [comment] 2015-11-08 13:56
@princejwesley Another problem. After rebuild I don't have interface such on version 2.0.1. This is my result. But in dev mode it's working correctly.
![mancy - repl 0 2015-11-08 15 54 33](https://cloud.githubusercontent.com/assets/1499594/11020726/4b9246b0-8631-11e5-8f65-43d1f0610268.png)

**Comment by princejwesley** [comment] 2015-11-08 16:30
@xgrommx let me try to reproduce it

**Comment by boneskull** [comment] 2015-11-08 19:31
@princejwesley This is not unique to windows; I have the same problem *but only when running with npm v3*

**Comment by pmros** [comment] 2015-11-08 19:31
Same problem here. But I'm using Linux.

I can run 
```
npm install
npm run package 
```
with no errors. Executable is generated at dist directory. But when I launch it, Mancy has no prompt (like xgrommx screenshot). However menu works (ie "About Mancy").

By the way, I uncommented [this line](https://github.com/princejwesley/Mancy/blob/master/gulpfile.babel.js#L262) and it worked OK (no crash). I use latest electron-prebuilt version (0.34.3).

**Comment by boneskull** [comment] 2015-11-08 19:40
cursory test against `master` (as of this writing) under NodeJS v5.0.0 with npm v3.3.6 fails.

**Comment by boneskull** [comment] 2015-11-08 19:41
best guess is that the code makes some assumptions about certain packages existing in `node_modules`, while npm v3 puts them somewhere else.

**Comment by princejwesley** [comment] 2015-11-08 20:03
@xgrommx Tried against node `v5.0.0` and npm `v3.3.12` in OSX. No issues. let me try it in linux

**Comment by pmros** [comment] 2015-11-08 20:08
node v5.0.0 and npm v3.3.12 in Linux (Arch Linux).

**Comment by boneskull** [comment] 2015-11-08 20:39
@princejwesley did you `rm -rf node_modules` after switching versions?

**Comment by xgrommx** [comment] 2015-11-08 20:40
@princejwesley I rebuild it again, doesn't work.

**Comment by princejwesley** [comment] 2015-11-08 20:46
@boneskull No. I just gave npm install. let me try now.

**Comment by princejwesley** [comment] 2015-11-08 20:53
@boneskull I can reproduce it. thanks.

**Comment by princejwesley** [comment] 2015-11-08 20:57
Identified the issue. I'll fix and let you guys know

**Comment by princejwesley** [comment] 2015-11-08 22:33
@boneskull @xgrommx @pmros npm 3 flattens the dependency structure. Fixed gulp task to handle it.

**Comment by pmros** [comment] 2015-11-08 22:59
@princejwesley It work for me at Linux! So you could change note about Linux at README and add a Linux executable to next release (2.0.3). Good job! Thank you!

**Comment by princejwesley** [comment] 2015-11-08 23:07
@pmros its not working for me (elementary OS 0.3.1 Freya). `rm -rf node_modules` and `npm install` might help. I'll try that.

**Comment by pmros** [comment] 2015-11-09 08:52
This works for me:
```
cd dist/Mancy-linux-x64
./Mancy
```
But if I try to launch Mancy executable from another directory
```
./dist/Mancy-linux-x64/Mancy
```
I get a segmentation fault!

**Comment by princejwesley** [comment] 2015-11-09 11:36
@xgrommx please confirm the fix

**Comment by princejwesley** [comment] 2015-11-10 00:02
Closing it for now. Please feel free to open it if this issue is not resolved

**Closed by princejwesley** 2015-11-10 00:02 UTC
Labels: Infrastructure
